development:
  adapter: mysql2
  enconding: utf-8
  database: toy_app_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  enconding: utf-8
  database: toy_app_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

production:
  adapter: mysql2
  enconding: utf-8
  database: toy_app_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true
